name: Build React on S3
on:
  push:
      branches:
        - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          BRANCH_NAME: ${GITHUB_REF#refs/heads/}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/tests/test
          destination_dir: ${BRANCH_NAME}
          publish_branch: document
          exclude_assets: ".github,${BRANCH_NAME}/js/**.js,${BRANCH_NAME}/css/**.css"
